version: '3.8'

services:
  app:
    build: .
    container_name: pdf-summary
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db:/app/db
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
